### PR TITLE
Remove commercial technology targets

### PR DESCRIPTION
**Pull request by palmer-dabbelt**

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
@kasanovic This is trivial.  I can rewrite history if you'd like, but that's a bit more of a pain.

**Comment by colinschmidt** [comment]
This level of description needs to be private?

**Comment by palmer-dabbelt** [comment]
Here's Krste's email, that's why I tagged him as a reviewer

````
From:       krste@berkeley.edu
To:         palmer.dabbelt@eecs.berkeley.edu
Subject:    removing tech path names from public repo
Date:       Tue, 04 Apr 2017 03:40:04 PDT (-0700)
Message-ID: <m260ikbgmz.fsf@berkeley.edu>


Palmer,

The following files have path names into NDA tech files - I realize it
technically doesn't expose much because only the file names are given,
but we'll show up on searches (that TSMC does regularly now after the
Stanford tech file incident) and legally this is grey ground.

https://github.com/ucb-bar/plsi/blob/bar/src/technologies/tsmc28hpm.tech.json
https://github.com/ucb-bar/plsi/blob/bar/src/technologies/st28fdsoi.tech.json

I realize this makes the stuff harder to use, but that's life using
NDA tools.  The public library versions are fine to leave in as
examples to help guide people write these files.

This is urgent, and the bad thing is git holds these in repo history,
so would ideally scrub from there too.

Thanks,
Krste
````

**Comment by colinschmidt** [comment]
Thanks for the info.

**Comment by edwardcwang** [comment]
What are the "public library versions"?

**Comment by palmer-dabbelt** [comment]
The ones I didn't delete (SAED32 and OSU180)

**Pull request merged**
